# FDSA configuration exploiting KuaiRec's rich item attributes.
field_separator: "\t"
model: FDSA
dataset: kuairec_small
data_path: data
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
  inter: [user_id, item_id, timestamp, label, watch_ratio, play_duration, video_duration]
  item:
    - item_id
    - author_id
    - video_type
    - upload_type
    - video_duration
    - video_width
    - video_height
    - music_id
    - video_tag_id
    - show_cnt
    - show_user_num
    - play_cnt
    - play_user_num
    - play_duration
    - complete_play_cnt
    - valid_play_cnt
    - long_time_play_cnt
    - short_time_play_cnt
    - play_progress
    - like_cnt
    - comment_cnt
    - follow_cnt
    - share_cnt
    - download_cnt
    - tags
selected_features:
  - author_id
  - video_type
  - upload_type
  - video_duration
  - video_width
  - video_height
  - music_id
  - video_tag_id
  - show_cnt
  - show_user_num
  - play_cnt
  - play_user_num
  - play_duration
  - complete_play_cnt
  - valid_play_cnt
  - long_time_play_cnt
  - short_time_play_cnt
  - play_progress
  - like_cnt
  - comment_cnt
  - follow_cnt
  - share_cnt
  - download_cnt
  - tags
pooling_mode: 'mean'

# Sequential recommendation evaluation protocol.
eval_args:
  split: {"RS": [0.8, 0.1, 0.1]}
  group_by: user
  order: TO
  mode: full

metrics: [Recall, NDCG, MRR]
topk: [5, 10, 20]
valid_metric: Recall@10
metric_decimal_place: 4

# Training hyper-parameters.
epochs: 120
learning_rate: 0.0005
train_batch_size: 1024
eval_batch_size: 4096
neg_sampling:
  uniform: 1

# FDSA architecture.
MAX_ITEM_LIST_LENGTH: 200
hidden_size: 128
inner_size: 256
n_layers: 2
n_heads: 4
hidden_dropout_prob: 0.2
attn_dropout_prob: 0.2
hidden_act: 'gelu'
layer_norm_eps: 1.0e-12
initializer_range: 0.02
loss_type: CE

# Reproducibility & logging.
seed: 2020
reproducibility: true
device: cpu
log_wandb: false
checkpoint_dir: saved
